server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: "srm-academia"

scrape_configs:
  # Application logs
  - job_name: srm-academia-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: srm-academia
          app: srm-academia
          environment: production
          __path__: /var/log/app*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339

  # Access logs
  - job_name: srm-academia-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: srm-access
          app: srm-academia
          __path__: /var/log/access*.log
    pipeline_stages:
      - regex:
          expression: '(?P<ip>\S+) - (?P<user>\S+) \[(?P<timestamp>\S+ \+\d+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<bytes>\d+)'
      - labels:
          method:
          path:
          status:

  # Error logs
  - job_name: srm-academia-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: srm-error
          app: srm-academia
          __path__: /var/log/error*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<message>.*)'
      - labels:
          level:
      - timestamp:
          source: timestamp
          format: '2006/01/02 15:04:05'

  # All other logs (fallback)
  - job_name: srm-academia-other
    static_configs:
      - targets:
          - localhost
        labels:
          job: srm-other
          app: srm-academia
          __path__: /var/log/*.log
          __path_exclude__: /var/log/{app*.log,access*.log,error*.log}